### PR TITLE
Simplify playwright executor

### LINKED ISSUE #72: Executor not handling 1 exit code from Playwright
Plugin version: "@mands/nx-playwright": "0.1.26"
Playwright version: "playwright": "1.26.0"

When a playwright test fails using the `nx e2e <app-name>-e2e` command I would expect the playwright output to be logged to the console in a normal fashion, below is an example of "normal" output from playwright 

```
Running X tests using X workers

  ✓  3 [chromium] › src\example.spec.ts:23:3 › Playwright example tests @example-playwright › Console output should be retained (7s)

  X skipped
  X passed (55s)
Done in 56.75s.

```
However, I am noticing that whenever a single test fails that this is not the case, instead we see that all playwright output is logged in the following format as the playwright test command is returning a 1 exit code for failure:
image

Looking at the executor, I can see that the code is not running past the following line:
`const { stdout, stderr } = yield (0, util_1.promisify)(child_process_1.exec)(command);`

Instead, as a 1 exit code is being returned from playwright, I'm assuming the promisify call is being rejected, therefore meaning we go straight to the catch block where `console.error('Unexpected error', error);` is ran, resulting in the errors being logged into the console as seen above. 

## To reproduce

1. Use the @mands/nx-playwright generator to add playwright to your project
2. Run a single test through the @mands/nx-playwright executor where you would expect that test to fail

## Expected behaviour

1. For a failed test, the code should not fall into the 'catch' block, only going into that block for errors unrelated to test failure
2. Formatting of any playwright output should be retained and logged to the console in a normal fashion.

### PR DESCRIPTION
**Pull request by andreacaldera**
## Problem

<sup>Fixes #72 </sup>

## Solution

Simplify executor and remove unnecessary code

## Additional changes

Refactor input `proj` to `testProject`

### Useful documentation

- [Contributing guidelines](/marksandspencer/nx-plugins/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Danphillipz** [comment]
Hi @andreacaldera, can see you have started a rework of the executor. Was this with the intention to resolve issues such as #72? I've got a colleague looking into that as we speak, who has also raised #76 which would conflict if that is not merged first

**Comment by andreacaldera** [comment]
Hey @Danphillipz , yes the new executor will potentially fix the other issues but I didn't have time to look into that properly yet. I'll make sure to test that once I get something working
If you got something ready on #76 we could merge that and then I can sort out conflict whenever the rewrite is ready

File: packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ export interface PlaywrightExecutorSchema {
   reporter?: string;
   browser?: 'chromium' | 'firefox' | 'webkit' | 'all';
   packageRunner?: PackageRunner;
-  proj?: string;
+  testProject?: string;
```
Comment (michaldudek) [inline packages/nx-playwright/src/executors/playwright-executor/schema-types.d.ts:15]: In my PR #76 I also added `--proj` to `README.md` so I guess it needs updating there, too :)

**Review by aamir-mns — APPROVED** [review]

**Review by aamir-mns — APPROVED** [review]
